import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import CustomCursor from "@/components/CustomCursor";

import Header from "@/components/Header";
import ScrollProgressBar from "@/components/ScrollProgressBar";
import Preloader from "@/components/Preloader";
const peyda = localFont({
  src: [
    {
      path: "./fonts/CreatoDisplay-Black.woff2",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/CreatoDisplay-ExtraBold.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "./fonts/CreatoDisplay-Bold.woff2",
      weight: "700",
      style: "normal",
    },

    {
      path: "./fonts/CreatoDisplay-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/CreatoDisplay-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/CreatoDisplay-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/Deutschlands.ttf",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-peyda",
});
export const metadata: Metadata = {
  title: "Beheshtian",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png", // or .png or .svg
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={peyda.variable}>
        <Header />
        <ScrollProgressBar />
        <CustomCursor />
        <Preloader />
        {children}
      </body>
    </html>
  );
}
